# Stage 1: build Expo web assets
FROM alpine:3.20 AS builder

RUN apk add --no-cache nodejs npm

WORKDIR /app

RUN apk upgrade --no-cache

ARG EXPO_PUBLIC_API_URL
ARG EXPO_PUBLIC_ALLOWED_DOMAIN
ARG EXPO_PUBLIC_GOOGLE_CLIENT_ID_EXPO
ARG EXPO_PUBLIC_GOOGLE_CLIENT_ID_WEB
ARG EXPO_PUBLIC_GOOGLE_CLIENT_ID_ANDROID
ARG EXPO_PUBLIC_GOOGLE_CLIENT_ID_IOS
ARG EXPO_PUBLIC_AUTH0_DOMAIN
ARG EXPO_PUBLIC_AUTH0_CLIENT_ID
ARG EXPO_PUBLIC_AUTH0_CONNECTION

ENV EXPO_PUBLIC_API_URL=$EXPO_PUBLIC_API_URL
ENV EXPO_PUBLIC_ALLOWED_DOMAIN=$EXPO_PUBLIC_ALLOWED_DOMAIN
ENV EXPO_PUBLIC_GOOGLE_CLIENT_ID_EXPO=$EXPO_PUBLIC_GOOGLE_CLIENT_ID_EXPO
ENV EXPO_PUBLIC_GOOGLE_CLIENT_ID_WEB=$EXPO_PUBLIC_GOOGLE_CLIENT_ID_WEB
ENV EXPO_PUBLIC_GOOGLE_CLIENT_ID_ANDROID=$EXPO_PUBLIC_GOOGLE_CLIENT_ID_ANDROID
ENV EXPO_PUBLIC_GOOGLE_CLIENT_ID_IOS=$EXPO_PUBLIC_GOOGLE_CLIENT_ID_IOS
ENV EXPO_PUBLIC_AUTH0_DOMAIN=$EXPO_PUBLIC_AUTH0_DOMAIN
ENV EXPO_PUBLIC_AUTH0_CLIENT_ID=$EXPO_PUBLIC_AUTH0_CLIENT_ID
ENV EXPO_PUBLIC_AUTH0_CONNECTION=$EXPO_PUBLIC_AUTH0_CONNECTION

COPY package*.json ./
RUN npm ci --no-audit --no-fund

COPY . .
RUN npm run build:web

# Stage 2: serve static files with Nginx
FROM alpine:3.20 AS runner

RUN apk add --no-cache nginx

COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
