import { StyleSheet } from "react-native";
import theme from "../styles/theme";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.white,
  },
  contentWrapper: {
    flex: 1,
    alignItems: "center",
    justifyContent: "flex-start",
    paddingTop: 56,
    paddingHorizontal: 20,
  },
  scrollView: {
    width: "100%",
  },
  header: {
    width: "100%",
    backgroundColor: theme.colors.white,
    borderWidth: 1,
    borderColor: "#E0E0E0",
    borderRadius: 14,
    paddingVertical: 14,
    paddingHorizontal: 16,
    marginBottom: 18,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  logoImage: {
    width: 50,
    height: 50,
  },
  headerText: {
    flex: 1,
  },
  title: {
    fontSize: 30,
    fontWeight: "700",
    color: theme.colors.primary,
  },
  subtitle: {
    fontSize: 20,
    fontWeight: "600",
    marginTop: 2,
    color: theme.colors.primary,
  },
  caption: {
    fontSize: 13,
    marginTop: 4,
    color: theme.colors.primaryMid,
  },
  formCard: {
    width: "100%",
    borderWidth: 1,
    borderColor: "#E0E0E0",
    borderRadius: 12,
    padding: 14,
    backgroundColor: "#F5F5F5",
    marginBottom: 16,
  },
  formTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: theme.colors.primary,
    marginBottom: 10,
  },
  input: {
    borderWidth: 1,
    borderColor: "#E0E0E0",
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 14,
    color: theme.colors.primary,
    backgroundColor: theme.colors.white,
    marginBottom: 10,
  },
  inputMultiline: {
    minHeight: 84,
    textAlignVertical: "top",
  },
  formMessage: {
    fontSize: 13,
    color: theme.colors.primaryMid,
    marginBottom: 8,
  },
  button: {
    backgroundColor: theme.colors.primary,
    borderRadius: 10,
    paddingVertical: 12,
    alignItems: "center",
  },
  buttonPressed: {
    opacity: 0.9,
  },
  buttonDisabled: {
    opacity: 0.6,
  },
  buttonText: {
    color: theme.colors.white,
    fontSize: 15,
    fontWeight: "700",
  },
  list: {
    gap: 12,
    paddingBottom: 24,
    alignItems: "stretch",
    width: "100%",
  },
  card: {
    width: "100%",
    borderWidth: 1,
    borderColor: "#E0E0E0",
    borderRadius: 12,
    padding: 14,
    backgroundColor: "#F5F5F5",
  },
  eventTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: theme.colors.primary,
  },
  eventDate: {
    fontSize: 14,
    color: theme.colors.primaryMid,
    marginTop: 4,
  },
  eventDescription: {
    fontSize: 14,
    color: theme.colors.primary,
    marginTop: 8,
    lineHeight: 20,
  },
  eventLocation: {
    fontSize: 13,
    color: theme.colors.primaryMid,
    marginTop: 8,
    fontWeight: "600",
  },
  eventAuthor: {
    fontSize: 13,
    color: theme.colors.primaryMid,
    marginTop: 10,
    fontWeight: "500",
  },
  empty: {
    marginTop: 16,
    color: theme.colors.primaryMid,
    textAlign: "center",
  },
  error: {
    color: "#b00020",
    marginBottom: 12,
    textAlign: "center",
  },
  navButton: {
    width: "100%",
    backgroundColor: theme.colors.primary,
    borderRadius: 0,
    paddingVertical: 24,
    paddingHorizontal: 20,
    alignItems: "center",
    marginTop: 0,
    paddingBottom: 44,
    paddingTop: 24,
    minHeight: 80,
  },
  navButtonText: {
    color: "#ffffff",
    fontSize: 20,
    fontWeight: "700",
  },
  // Estilos para header con botón
  headerWithButton: {
    width: "100%",
    backgroundColor: theme.colors.white,
    borderWidth: 1,
    borderColor: "#E0E0E0",
    borderRadius: 14,
    paddingVertical: 14,
    paddingHorizontal: 16,
    marginBottom: 18,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  createButton: {
    backgroundColor: theme.colors.primary,
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 8,
  },
  createButtonText: {
    color: "#ffffff",
    fontWeight: "700",
    fontSize: 13,
  },
  // Estilos del Modal
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContent: {
    width: "85%",
    backgroundColor: "#FFF",
    borderRadius: 12,
    padding: 20,
    maxHeight: "90%",
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: theme.colors.primary,
  },
  closeButton: {
    padding: 8,
  },
  closeButtonText: {
    fontSize: 24,
    color: theme.colors.primary,
    fontWeight: "bold",
  },
});