import { StyleSheet } from "react-native";
import theme from "../styles/theme";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.white,
  },
  contentWrapper: {
    flex: 1,
    alignItems: "center",
    justifyContent: "flex-start",
    paddingTop: 56,
    paddingHorizontal: 20,
  },
  scrollView: {
    width: "100%",
  },
  header: {
    width: "100%",
    backgroundColor: theme.colors.white,
    borderWidth: 1,
    borderColor: "#E0E0E0",
    borderRadius: 14,
    paddingVertical: 14,
    paddingHorizontal: 16,
    marginBottom: 18,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  logoImage: {
    width: 50,
    height: 50,
  },
  headerText: {
    flex: 1,
  },
  title: {
    fontSize: 30,
    fontWeight: "700",
    color: theme.colors.primary,
  },
  subtitle: {
    fontSize: 20,
    fontWeight: "600",
    marginTop: 2,
    color: theme.colors.primary,
  },
  caption: {
    fontSize: 13,
    marginTop: 4,
    color: theme.colors.primaryMid,
  },
  sectionHeaderContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  createButton: {
    backgroundColor: theme.colors.primary,
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 8,
  },
  createButtonText: {
    color: "#ffffff",
    fontWeight: "700",
    fontSize: 13,
  },
  list: {
    gap: 12,
    paddingBottom: 24,
    alignItems: "stretch",
    width: "100%",
  },
  sectionCard: {
    width: "100%",
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E0E0E0",
    borderRadius: 12,
    padding: 12,
    marginBottom: 12,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: theme.colors.primary,
  },
  card: {
    width: "100%",
    borderWidth: 1,
    borderColor: "#E0E0E0",
    borderRadius: 12,
    padding: 14,
    backgroundColor: "#F5F5F5",
    marginBottom: 10,
  },
  groupTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: theme.colors.primary,
    marginBottom: 6,
  },
  groupMateria: {
    fontSize: 14,
    color: theme.colors.primaryMid,
    marginBottom: 8,
    fontWeight: "600",
  },
  groupMembers: {
    fontSize: 13,
    color: theme.colors.primaryMid,
    marginBottom: 8,
  },
  membersList: {
    marginTop: 4,
  },
  memberName: {
    fontSize: 13,
    color: theme.colors.primary,
    marginBottom: 2,
  },
  recursosContainer: {
    marginTop: 12,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: "#D9E1EA",
  },
  recursosHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  recursosTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: theme.colors.primary,
  },
  uploadButton: {
    backgroundColor: "#0A7F5A",
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
  },
  uploadButtonDisabled: {
    opacity: 0.5,
  },
  uploadButtonText: {
    color: "#ffffff",
    fontWeight: "700",
    fontSize: 12,
  },
  emptyResourceText: {
    fontSize: 13,
    color: theme.colors.primaryMid,
  },
  resourceItem: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: "#E7EDF3",
  },
  resourceInfo: {
    flex: 1,
    paddingRight: 10,
  },
  resourceName: {
    fontSize: 13,
    fontWeight: "600",
    color: theme.colors.primary,
  },
  resourceMeta: {
    fontSize: 12,
    color: theme.colors.primaryMid,
    marginTop: 2,
  },
  resourceTag: {
    fontSize: 11,
    fontWeight: "700",
    color: "#0A7F5A",
    backgroundColor: "#E8F7F1",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
  },
  joinButton: {
    marginTop: 10,
    backgroundColor: theme.colors.primary,
    borderRadius: 8,
    paddingVertical: 10,
    paddingHorizontal: 14,
    alignItems: "center",
  },
  joinButtonDisabled: {
    opacity: 0.5,
  },
  joinButtonText: {
    color: "#ffffff",
    fontWeight: "700",
    fontSize: 14,
  },
  empty: {
    marginTop: 16,
    color: theme.colors.primaryMid,
    textAlign: "center",
  },
  error: {
    color: "#b00020",
    marginBottom: 12,
    textAlign: "center",
    paddingHorizontal: 20,
  },
  navButton: {
    width: "100%",
    backgroundColor: theme.colors.primary,
    borderRadius: 0,
    paddingVertical: 24,
    paddingHorizontal: 20,
    alignItems: "center",
    marginTop: 0,
    paddingBottom: 46,
    paddingTop: 24,
    minHeight: 80,
  },
  navButtonText: {
    color: "#ffffff",
    fontSize: 20,
    fontWeight: "700",
  },
  // Estilos del Modal de Crear Grupo
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContent: {
    width: "85%",
    backgroundColor: "#FFF",
    borderRadius: 12,
    padding: 20,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: theme.colors.primary,
    marginBottom: 15,
  },
  input: {
    borderWidth: 1,
    borderColor: "#ccc",
    borderRadius: 8,
    padding: 10,
    marginBottom: 15,
    color: theme.colors.primary,
  },
  modalButtons: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 10,
  },
  modalButton: {
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 8,
    minWidth: 80,
    alignItems: "center",
  },
  modalButtonCancel: {
    backgroundColor: "#ccc",
  },
  modalButtonSubmit: {
    backgroundColor: theme.colors.primary,
  },
  materiaChip: {
    borderWidth: 1,
    borderColor: "#CCC",
    borderRadius: 20,
    paddingVertical: 6,
    paddingHorizontal: 12,
    backgroundColor: "#F5F5F5",
  },
  materiaChipSelected: {
    backgroundColor: theme.colors.primary,
    borderColor: theme.colors.primary,
  },
  materiaChipText: {
    fontSize: 13,
    color: "#666",
  },
  materiaChipTextSelected: {
    color: "#FFF",
    fontWeight: "bold",
  },
  errorCreacionText: {
    color: "#b00020",
    marginBottom: 12,
    textAlign: "center",
    fontSize: 13,
    fontWeight: "500",
  },
  modalSubtitle: {
    fontWeight: "bold",
    color: "#005b96",
    marginBottom: 8,
  },
  materiasContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 15,
  },
  emptyMateriasText: {
    fontSize: 13,
    color: "#666",
    fontStyle: "italic",
  },
  modalButtonTextCancel: {
    fontWeight: "bold",
    color: "#333",
  },
  modalButtonTextSubmit: {
    color: "#FFF",
    fontWeight: "bold",
  },
});
