import { StyleSheet } from 'react-native';
import theme from '../styles/theme';

export const styles = StyleSheet.create({
  // --- CONTENEDOR PRINCIPAL ---
  container: {
    flex: 1,
    backgroundColor: theme.colors.white,
  },

  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: theme.spacing?.md || 16,
    paddingTop: (theme.spacing?.xl || 40) + 16,
    paddingBottom: theme.spacing?.lg || 24,
    backgroundColor: theme.colors?.white || '#FFFFFF',
    borderBottomWidth: 1,
    borderBottomColor: '#E0E0E0',
  },
  headerLeft: {
    flex: 1,
    alignItems: 'flex-start',
    justifyContent: 'center',
    paddingLeft: 2,
  },
  headerCenter: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 14,
  },
  headerRight: {
    flex: 1,
    alignItems: 'flex-end',
    justifyContent: 'center',
  },
  brandLogo: {
    height: 56,
    minWidth: 160,
    alignSelf: 'flex-start',
    marginLeft: -30,
  },
  brand: {
    color: theme.colors?.gold || '#FFD700',
    fontSize: theme.typography?.fontSize?.lg || 20,
    fontWeight: 'bold',
  },
  iconButton: {
    width: 36,
    height: 36,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 18,
    backgroundColor: '#F2F7FF',
  },
  iconWithBadgeContainer: {
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'center',
  },
  notificationBadgeDot: {
    position: 'absolute',
    right: -2,
    top: -1,
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#E53935',
    borderWidth: 1,
    borderColor: '#FFFFFF',
  },
  logoutButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 9,
    paddingHorizontal: 12,
    borderRadius: 999,
    backgroundColor: '#003d70',
    borderWidth: 1,
    borderColor: '#003d70',
  },
  logoutText: {
    color: '#FFFFFF',
    fontWeight: '700',
    fontSize: 13,
  },

  mainContent: {
    flex: 1,
    padding: theme.spacing?.lg || 20,
  },
  greeting: {
    fontSize: theme.typography?.fontSize?.xl || 24,
    fontWeight: '700',
    color: theme.colors?.primary || '#333333',
    marginBottom: theme.spacing?.sm || 8,
  },
  subtitle: {
    fontSize: theme.typography?.fontSize?.md || 16,
    color: theme.colors?.primaryMid || '#666666',
    marginBottom: theme.spacing?.lg || 24,
  },
  searchContainer: {
    backgroundColor: '#FFFFFF',
    padding: 12,
    borderRadius: theme.radius?.md || 10,
    borderWidth: 1,
    borderColor: '#E0E0E0',
    marginBottom: theme.spacing?.md || 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 2,
  },
  searchInput: {
    fontSize: 16,
    color: '#333',
  },
  resultsContainer: {
    flex: 1,
    marginTop: 10,
  },
  resultsTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#888',
    marginBottom: 10,
  },
  userResultCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#EEF1F4',
  },
  userResultInfo: {
    flex: 1,
    paddingRight: 8,
  },
  userResultName: {
    fontWeight: '700',
    fontSize: 15,
    color: '#0F172A',
  },
  userResultEmail: {
    marginTop: 2,
    color: '#475569',
    fontSize: 13,
  },
  sendRequestButton: {
    backgroundColor: '#003d70',
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 12,
    minWidth: 110,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sendRequestButtonDisabled: {
    opacity: 0.6,
  },
  sendRequestButtonText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '700',
  },
  userStatusBadge: {
    borderWidth: 1,
    borderColor: '#CBD5E1',
    borderRadius: 8,
    paddingVertical: 7,
    paddingHorizontal: 12,
    backgroundColor: '#F8FAFC',
  },
  userStatusBadgeText: {
    color: '#475569',
    fontSize: 12,
    fontWeight: '700',
  },

  onboardingBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(2, 6, 23, 0.62)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  onboardingBackdropTop: {
    justifyContent: 'flex-start',
    paddingTop: 78,
  },
  onboardingBackdropBottom: {
    justifyContent: 'flex-end',
    paddingBottom: 112,
  },
  onboardingCard: {
    width: '100%',
    maxWidth: 420,
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    paddingHorizontal: 24,
    paddingVertical: 28,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 0.18,
    shadowRadius: 22,
    elevation: 10,
  },
  onboardingStepCounter: {
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 1,
    textTransform: 'uppercase',
    color: '#64748B',
    marginBottom: 12,
  },
  onboardingIconWrap: {
    width: 68,
    height: 68,
    borderRadius: 34,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#EAF3FF',
    marginBottom: 18,
  },
  onboardingTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: '#0F172A',
    marginBottom: 10,
  },
  onboardingDescription: {
    fontSize: 15,
    lineHeight: 22,
    color: '#475569',
  },
  onboardingDotsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 22,
  },
  onboardingDot: {
    width: 8,
    height: 8,
    borderRadius: 999,
    backgroundColor: '#CBD5E1',
  },
  onboardingDotActive: {
    width: 24,
    backgroundColor: '#007AFF',
  },
  onboardingActions: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    marginTop: 28,
  },
  onboardingSecondaryButton: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#CBD5E1',
    borderRadius: 14,
    paddingVertical: 13,
    alignItems: 'center',
    justifyContent: 'center',
  },
  onboardingSecondaryButtonText: {
    fontSize: 15,
    fontWeight: '600',
    color: '#334155',
  },
  onboardingPrimaryButton: {
    flex: 1,
    borderRadius: 14,
    paddingVertical: 13,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#007AFF',
  },
  onboardingPrimaryButtonText: {
    fontSize: 15,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  onboardingHighlightedElement: {
    borderWidth: 3,
    borderColor: '#F8FAFC',
    backgroundColor: '#FFFFFF',
    transform: [{ scale: 1.08 }],
    shadowColor: '#93C5FD',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.95,
    shadowRadius: 24,
    elevation: 18,
    zIndex: 4,
  },
  onboardingHighlightedPrimaryElement: {
    borderWidth: 3,
    borderColor: '#DBEAFE',
    transform: [{ scale: 1.03 }],
    shadowColor: '#60A5FA',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.9,
    shadowRadius: 26,
    elevation: 18,
    zIndex: 4,
  },
  onboardingHighlightedBar: {
    borderTopWidth: 3,
    borderTopColor: '#DBEAFE',
    borderWidth: 2,
    borderColor: '#BFDBFE',
    shadowColor: '#60A5FA',
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.7,
    shadowRadius: 24,
    elevation: 18,
    zIndex: 4,
  },


  bottomBar: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    backgroundColor: theme.colors?.primary,
    paddingVertical: 24,
    paddingHorizontal: 12,
    borderTopWidth: 1,
    borderTopColor: '#E0E0E0',
    paddingBottom: 48,
    paddingTop: 24,
    width: '100%',
    alignSelf: 'stretch',
    minHeight: 80,
  },
  navButton: {
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 8,
  },
  navButtonText: {
    color: theme.colors?.white || '#FFFFFF',
    fontWeight: '600',
    fontSize: 20,
  },
  footerTab: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 8,
    borderRadius: 999,
  },
  footerTabActive: {
    backgroundColor: 'rgba(255, 255, 255, 0.18)',
  },
  footerIcon: {
    color: theme.colors?.white || '#FFFFFF',
  },
  navButtonTextActive: {
    fontWeight: '700',
  }
});