/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/eventos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar eventos globales (opcionalmente filtrar por categoría) */
        get: {
            parameters: {
                query?: {
                    categoria?: "academico" | "cultural" | "deportivo" | "otro";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Lista de eventos */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: components["schemas"]["Evento"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Crear un evento */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        titulo: string;
                        descripcion: string;
                        lugar?: string;
                        /** Format: date-time */
                        fechaEvento: string;
                        /** @enum {string} */
                        categoria?: "academico" | "cultural" | "deportivo" | "otro";
                    };
                };
            };
            responses: {
                /** @description Evento creado */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: components["schemas"]["Evento"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/eventos/suscripciones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar categorías suscritas por el usuario */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Categorías suscritas */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** Suscribirse a una categoría de eventos */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        categoria: "academico" | "cultural" | "deportivo" | "otro";
                    };
                };
            };
            responses: {
                /** @description Suscripción registrada */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/eventos/suscripciones/{categoria}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Desuscribirse de una categoría de eventos */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    categoria: "academico" | "cultural" | "deportivo" | "otro";
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Desuscripción exitosa */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/foro/{materiaId}/preguntas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener preguntas del foro de una materia */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    materiaId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Lista de preguntas */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: components["schemas"]["ForoPregunta"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Publicar una pregunta en el foro */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    materiaId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        titulo: string;
                        contenido: string;
                    };
                };
            };
            responses: {
                /** @description Pregunta creada */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: components["schemas"]["ForoPregunta"];
                        };
                    };
                };
                /** @description Sin matrícula activa */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/foro/preguntas/{preguntaId}/respuestas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener respuestas de una pregunta ordenadas por puntuación */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    preguntaId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Lista de respuestas */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: components["schemas"]["ForoRespuesta"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Publicar una respuesta a una pregunta */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    preguntaId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        contenido: string;
                        materiaId: string;
                    };
                };
            };
            responses: {
                /** @description Respuesta creada */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/foro/respuestas/{respuestaId}/votos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Votar una respuesta (1 positivo, -1 negativo) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    respuestaId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {integer} */
                        valor: 1 | -1;
                    };
                };
            };
            responses: {
                /** @description Respuesta con puntuación actualizada */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: components["schemas"]["ForoRespuesta"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sesiones/series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Crear una serie de sesiones de estudio recurrentes */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        titulo: string;
                        descripcion: string;
                        lugar: string;
                        /** @enum {string} */
                        frecuencia: "DIARIA" | "SEMANAL" | "QUINCENAL";
                        /** Format: date-time */
                        fechaInicio: string;
                        /** Format: date-time */
                        fechaFin: string;
                        /** @default 30 */
                        recordatorioMinutos?: number;
                    };
                };
            };
            responses: {
                /** @description Serie creada con todas sus instancias */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: components["schemas"]["SerieEstudio"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sesiones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener sesiones activas del usuario autenticado */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Lista de sesiones no canceladas */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: components["schemas"]["SesionEstudio"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sesiones/{sesionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Modificar una sesión con alcance solo_esta o esta_y_siguientes */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    sesionId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        alcance: "solo_esta" | "esta_y_siguientes";
                        titulo?: string;
                        descripcion?: string;
                        lugar?: string;
                        /** Format: date-time */
                        fecha?: string;
                        recordatorioMinutos?: number;
                    };
                };
            };
            responses: {
                /** @description Sesión(es) actualizada(s) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/api/sesiones/{sesionId}/cancelar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancelar una sesión con alcance solo_esta o esta_y_siguientes */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    sesionId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        alcance: "solo_esta" | "esta_y_siguientes";
                    };
                };
            };
            responses: {
                /** @description Sesión(es) cancelada(s) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /** @example false */
            success?: boolean;
            message?: string;
        };
        Usuario: {
            id?: string;
            nombre?: string;
            apellido?: string;
            /** Format: email */
            correo?: string;
            carrera?: string;
            semestre?: number;
        };
        ForoPregunta: {
            id?: string;
            titulo?: string;
            contenido?: string;
            autorId?: string;
            autorNombre?: string;
            materiaId?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        ForoRespuesta: {
            id?: string;
            contenido?: string;
            autorId?: string;
            autorNombre?: string;
            preguntaId?: string;
            puntuacion?: number;
            /** Format: date-time */
            createdAt?: string;
        };
        SesionEstudio: {
            id?: string;
            titulo?: string;
            descripcion?: string;
            lugar?: string;
            /** Format: date-time */
            fecha?: string;
            recordatorioMinutos?: number;
            cancelada?: boolean;
            modificada?: boolean;
            serieId?: string;
            creadorId?: string;
        };
        SerieEstudio: {
            id?: string;
            titulo?: string;
            descripcion?: string;
            lugar?: string;
            /** @enum {string} */
            frecuencia?: "DIARIA" | "SEMANAL" | "QUINCENAL";
            /** Format: date-time */
            fechaInicio?: string;
            /** Format: date-time */
            fechaFin?: string;
            recordatorioMinutos?: number;
            sesiones?: components["schemas"]["SesionEstudio"][];
        };
        Evento: {
            id?: string;
            titulo?: string;
            descripcion?: string;
            lugar?: string;
            /** Format: date-time */
            fechaEvento?: string;
            /** @enum {string} */
            categoria?: "academico" | "cultural" | "deportivo" | "otro";
            creadorId?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
