import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    centerText: {
        textAlign: 'center',
        color: '#64748b',
        fontSize: 15,
        paddingHorizontal: 20,
        marginTop: 16,
    },
    listContent: {
        paddingTop: 4,
        paddingBottom: 20,
    },
    screenHeader: {
        marginBottom: 12,
    },
    solicitudesSection: {
        marginTop: 16,
        padding: 14,
        borderWidth: 1,
        borderColor: '#dbe6f2',
        borderRadius: 12,
        backgroundColor: '#f7fbff',
    },
    solicitudesTitle: {
        fontSize: 16,
        fontWeight: '700',
        color: '#002855',
        marginBottom: 10,
    },
    solicitudVaciaText: {
        fontSize: 14,
        color: '#64748b',
    },
    solicitudCard: {
        backgroundColor: '#fff',
        borderWidth: 1,
        borderColor: '#e1e9f3',
        borderRadius: 10,
        padding: 12,
        marginBottom: 10,
    },
    solicitudInfo: {
        marginBottom: 10,
    },
    solicitudNombre: {
        fontSize: 15,
        fontWeight: '700',
        color: '#002855',
    },
    solicitudCorreo: {
        fontSize: 13,
        color: '#5e6f84',
        marginTop: 2,
    },
    solicitudActions: {
        flexDirection: 'row',
        columnGap: 10,
    },
    aceptarButton: {
        backgroundColor: '#003d70',
        paddingVertical: 8,
        paddingHorizontal: 14,
        borderRadius: 8,
    },
    aceptarButtonText: {
        color: '#fff',
        fontWeight: '600',
    },
    rechazarButton: {
        backgroundColor: '#bb4b4e',
        paddingVertical: 8,
        paddingHorizontal: 14,
        borderRadius: 8,
    },
    rechazarButtonText: {
        color: '#fff',
        fontWeight: '600',
    },
    card: {
        backgroundColor: '#fff',
        borderRadius: 12,
        padding: 18,
        marginBottom: 16,
        shadowColor: '#002855',
        shadowOpacity: 0.08,
        shadowRadius: 6,
        elevation: 3,
        borderWidth: 1,
        borderColor: '#e0e7ef',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    infoContainer: {
        flex: 1,
        marginRight: 12,
    },
    name: {
        fontWeight: 'bold',
        fontSize: 17,
        color: '#002855',
        marginBottom: 2,
    },
    email: {
        color: '#666',
        fontSize: 15,
    },
    messageButton: {
        backgroundColor: '#002855',
        paddingVertical: 8,
        paddingHorizontal: 14,
        borderRadius: 8,
    },
    messageButtonText: {
        color: '#fff',
        fontWeight: '600',
        fontSize: 14,
    },
    searchResultMessageButton: {
        backgroundColor: '#002855',
        paddingVertical: 10,
        paddingHorizontal: 12,
        borderRadius: 8,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 4,
    },
    searchResultMessageButtonText: {
        color: '#fff',
        fontWeight: '600',
        fontSize: 13,
    },
    searchContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#f0f4f9',
        borderRadius: 10,
        paddingHorizontal: 12,
        paddingVertical: 10,
        marginBottom: 16,
        marginHorizontal: 0,
        borderWidth: 1,
        borderColor: '#dbe6f2',
    },
    searchIcon: {
        marginRight: 10,
    },
    searchInput: {
        flex: 1,
        fontSize: 16,
        color: '#002855',
        padding: 0,
    },
    searchResultsContainer: {
        backgroundColor: '#fff',
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#dbe6f2',
        marginBottom: 16,
        padding: 12,
    },
    searchResultsList: {
        paddingVertical: 4,
    },
    searchResultCard: {
        backgroundColor: '#f7fbff',
        borderRadius: 10,
        padding: 14,
        marginBottom: 10,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#e1e9f3',
    },
    searchResultActions: {
        flexDirection: 'row',
        gap: 8,
        alignItems: 'center',
    },
    addButton: {
        backgroundColor: '#0066b3',
        paddingVertical: 10,
        paddingHorizontal: 12,
        borderRadius: 8,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 4,
    },
    addButtonText: {
        color: '#fff',
        fontWeight: '600',
        fontSize: 13,
    },
});